### ISSUE TITLE
Исправить баги в стихотворении Пушкина

### ISSUE THREAD

**Issue by linalex13666** [Java-Mens/SuperRepo#1]
Я читала стихотворение и там оказалось много пропущенных строчек. Кто-нибудь будет исправлять?

**Comment by Drovie** [comment]
Да, правда, пропущена строчка с русалкой, и Бабой Ягой

**Comment by kaimakov-rk** [comment]
Подтверждаю. Давайте исправлять)

**Comment by kaimakov-rk** [comment]
Ой

**Comment by linalex13666** [comment]
эбе

**Comment by Dev-Atom42** [comment]
Вы что наделали, аболтусы?
Без зарплаты остаётесь!

**Comment by linalex13666** [comment]
яхшэ

**Comment by Drovie** [comment]
Баг исправлен

**Comment by Dev-Atom42** [comment]
Принято!
